@startuml strategy
    title Strategy Design Pattern

    class ImplAStrategy {
        +DoSomething()
    }
    class ImplBStrategy{
        +DoSomething()
    }
    class ImplCStrategy{
        +DoSomething()
    }
    class Client{
        -_doSomething
        +DoSomething()
    }

    Client o---^ IStrategy
    IStrategy <|-- ImplAStrategy
    IStrategy <|-- ImplBStrategy
    IStrategy <|-- ImplCStrategy

    note right of Client::DoSomething
        In Dosomething call => _doSomething.Dosomething();
    end note

    interface IStrategy {
        DoSomething()
    }

@enduml